using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCompanyAttribute("CM Awesome Sauce")]
[assembly: AssemblyVersionAttribute("0.2.0.0")]
[assembly: AssemblyFileVersionAttribute("0.2.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.2.0.0")]
[assembly: AssemblyTitleAttribute("FubuDinner")]
[assembly: AssemblyProductAttribute("FubuDinner")]
[assembly: AssemblyDescriptionAttribute("FubuDinner is a product of CM Awesome Sauce - git://github.com/chadmyers/fubudinn" +
    "er.git.")]
[assembly: AssemblyTrademarkAttribute("FubuDinner - CM Awesome Sauce")]
[assembly: AssemblyCopyrightAttribute("Copyright 2010 CM Awesome Sauce, - Original author or authors")]

